// File generated by hand (FlutterFire CLI unavailable in this environment —
// Firebase project/app registration was done via console instead of `flutterfire configure`).
// If you ever get the CLI working, `flutterfire configure` will overwrite this safely.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios — register an iOS app in the Firebase console first.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyCztPQFenag8yuam43jafGCiX4w8_agdYc',
    appId: '1:1040355220585:android:181f8b0d73bdc8f13f16f8',
    messagingSenderId: '1040355220585',
    projectId: 'projecterrand',
    storageBucket: 'projecterrand.firebasestorage.app',
  );

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyCED1EjeHbHsV8jBl36swlUeHKCeMmTCtI',
    appId: '1:1040355220585:web:0b92f4ddb9a06af43f16f8',
    messagingSenderId: '1040355220585',
    projectId: 'projecterrand',
    authDomain: 'projecterrand.firebaseapp.com',
    storageBucket: 'projecterrand.firebasestorage.app',
    measurementId: 'G-T8QZQ7FHMC',
  );
}
