// File generated by hand (FlutterFire CLI unavailable in this environment —
// Firebase project/app registration was done via console instead of `flutterfire configure`).
// If you ever get the CLI working, `flutterfire configure` will overwrite this safely.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // Windows 데스크톱은 웹 앱과 같은 자격 증명을 쓴다. Firebase 콘솔에 따로
      // 'Windows 앱'을 등록하는 항목이 없고, 데스크톱 SDK가 웹 API 키로 동작하기 때문이다.
      // (콘솔 > 인증 > 승인된 도메인에 localhost가 있어야 로그인이 된다)
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos — register a macOS app in the Firebase console first.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios — register an iOS app in the Firebase console first.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyCztPQFenag8yuam43jafGCiX4w8_agdYc',
    appId: '1:1040355220585:android:181f8b0d73bdc8f13f16f8',
    messagingSenderId: '1040355220585',
    projectId: 'projecterrand',
    storageBucket: 'projecterrand.firebasestorage.app',
  );

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyCED1EjeHbHsV8jBl36swlUeHKCeMmTCtI',
    appId: '1:1040355220585:web:0b92f4ddb9a06af43f16f8',
    messagingSenderId: '1040355220585',
    projectId: 'projecterrand',
    authDomain: 'projecterrand.firebaseapp.com',
    storageBucket: 'projecterrand.firebasestorage.app',
    measurementId: 'G-T8QZQ7FHMC',
  );

  /// Windows 데스크톱. 웹 앱 자격 증명을 그대로 쓴다.
  static const windows = web;
}
